version: '3'

services:
  app:
    image: whatsapp-bot-twilio
    build:
      context: .
      args:
        NGROK_AUTH_TOKEN: ${NGROK_AUTH_TOKEN}
    env_file:
      - .env
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
    volumes:
      - ./:/app
      - ./srcs/:/app
    ports:
      - "8080:8080"
