version: '3'

services:
  backend:
    build:
      context: ./dockers
      dockerfile: backend.Dockerfile
    volumes:
      - ./testRepo/backend/:/app/backend
    networks:
      - app-network
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./dockers
      dockerfile: frontend.Dockerfile
    volumes:
      - ./testRepo/frontend:/app/frontend/
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

#  app:
#    build:
#      context: .
#    volumes:
#      - ./srcs:/app/srcs
#    ports:
#      - "3000:3000"
